name: Database Migration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    env:
      TF_VAR_rdsUsername: ${{ secrets.DB_USERNAME }}
      TF_VAR_rdsPassword: ${{ secrets.DB_PASSWORD }}
      TF_VAR_rdsName: ${{ secrets.DB_NAME }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color    

      - name: Plan Terraform
        id: tfplan
        run: terraform plan out=tfplan
            
      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve
