name: Database Migration

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          
      - name: Terraform fmt
        id: fmt
        run: |
          cd terraform
          terraform fmt -check  

      - name: Initialize Terraform
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color    

      - name: Plan Terraform
        id: plan
        run: terraform plan -out=tfplan
            
      - name: Apply Terraform
        id: apply
        run: |
          terraform apply -auto-approve tfplan | tee output.txt
          echo "::set-output name=POSTGRES_ENDPOINT::$(terraform output -raw postgres_db_endpoint)"  >> $GITHUB_OUTPUT
