name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory with resources to be destroyed'
        required: true
        default: 'terraform'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform   

      - name: Destroy Terraform
        run: terraform apply -destroy -auto-approve
        working-directory: ./terraform
