name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory with resources to be destroyed'
        required: true
        default: 'terraform'
    

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Destroy Terraform
        run: |
          cd terraform
          terraform destroy -auto-approve
