name: Destroy Database

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory with resources to be destroyed'
        required: true
        default: 'terraform'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-latest
    name: Destroy Infrastructure DB
    env:
      TF_WORKING_DIR: ${{ github.event.inputs.dir }}
      TF_VAR_rds_database_name: ${{ secrets.DB_NAME }}
      TF_VAR_rds_user_name: ${{ secrets.DB_USERNAME }}
      TF_VAR_rds_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_account: ${{ secrets.AWS_ACCOUNT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init -reconfigure -upgrade
        working-directory: ./terraform   

      - name: Destroy Terraform
        run: terraform apply -destroy -auto-approve
        working-directory: ./terraform
