name: Migração dos Dados

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Migration Data Base Postgresql with FlyWay'
        required: true
        default: 'db'

jobs:
  migrate_database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Flyway Endpoint
        run: |
            if [ -z "${POSTGRES_ENDPOINT}" ]; then
              echo "POSTGRES_ENDPOINT=${{ needs.deploy_infrastructure.outputs.postgres_endpoint }}" >> $GITHUB_ENV
            fi
          
      - name: Database Migration
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ env.POSTGRES_ENDPOINT }}:5432/restaurante
          user: ${{ secrets.POSTGRES_USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          locations: filesystem:./db
      - run: echo 'Fazendo migração dos dados....'
