name: Migração dos Dados

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Migration Data Base Postgresql with FlyWay'
        required: true
        default: 'db'

jobs:
  migrate_database:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create Database
        run: |
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h ${{ secrets.DB_ENDPOINT }} -U ${{ secrets.DB_USERNAME }} -tc "SELECT 1 FROM pg_database WHERE datname = '${{ secrets.DB_NAME }}'" | grep -q 1 | psql -U postgres -c "CREATE DATABASE ${{ secrets.DB_NAME }};" 

      - name: Install Flyway CLI
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.6/flyway-commandline-8.5.6-linux-x64.tar.gz | tar xvz && \
          sudo mv flyway-8.5.6 /opt/flyway && \
          sudo ln -s /opt/flyway/flyway /usr/local/bin/flyway
          
      - name: Run Flyway Migrations
        run: flyway -url=jdbc:postgresql://${{ secrets.DB_ENDPOINT }}:5432/restaurante -user=${{ secrets.POSTGRES_USERNAME }} -password=${{ secrets.POSTGRES_PASSWORD }} -locations=filesystem:db migrate

