name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    env:
      TF_VAR_postgres_username: ${{ secrets.POSTGRES_USERNAME }}
      TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init ./terraform

      - name: Plan Terraform
        run: terraform plan -out=tfplan ./terraform

      - name: Apply Terraform
        id: terraform_apply
        run: |
          terraform apply -auto-approve ./terraform | tee output.txt
          echo "::set-output name=postgres_endpoint::$(terraform output -raw postgres_db_endpoint)"
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

      - name: Persist PostgreSQL Endpoint
        run: echo "POSTGRES_ENDPOINT=${{ steps.terraform_apply.outputs.postgres_endpoint }}" >> $GITHUB_ENV

  
  migrate_database:
    needs: deploy_infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flyway
        uses: flyway/setup-flyway@v1
        with:
          version: '7.15.0'

      - name: Database Migration
        run: |
          flyway -url=jdbc:postgresql://${{ env.POSTGRES_ENDPOINT }}:5432/my-postgres-db -user=admin -password=mysecretpassword migrate
